### ISSUE TITLE
how to close trace message?

### ISSUE THREAD

**Issue by Rain-31** [johandry/terranova#17]
how to close trace message?

**Comment by johandry** [comment]
please, explain. Could you provide more details?

**Comment by johandry** [comment]
If you meant to not print the Terraform logs, there is a way to do it and this issue is related to issue #8 

With the future PR from the branch `feat/issue-8/johandry/logger` the developer/user of Terranova can provide a custom logger, this custom logger can be one to discard every Terraform output.

I have not completed the PR because I'm not happy with the solution yet but I'll create it soon and hopefully wait for some feedback or thoughts from the community, maybe there is a better way to solve the problems that I've found (described in this future PR).

I'll update this issue as soon as the PR is created. Thanks a lot for you feedback and support. :)

**Comment by Rain-31** [comment]
i mean TF_LOG doesn't work

**Comment by johandry** [comment]
The PR #19 will fix this issue. 
I'll add more documentation about how to use it and maybe more tests before merge it.
