### ISSUE TITLE
[BUG] Unable to get a working demo

### ISSUE THREAD

**Issue by cacois** [johandry/terranova#30]
First of all, great project! Seriously cool. 

I believe this is just a bit of lagging documentation, but I'm unable to find a set of versions for terranova/terraform/providers that work happily together. The closest I have found is:

github.com/johandry/terranova v0.0.3 (I also tried 0.0.2, they run ito the same bug)
github.com/hashicorp/terraform v0.12.17 (as specified at the top of the readme, expecting terranova 0.0.2)
github.com/terraform-providers/terraform-provider-aws v1.60.1-0.20191003145700-f8707a46c6ec  (as specified in readme, compatible providers section)

Which seems to almost work but results in this error:

```
$ go get
# github.com/terraform-providers/terraform-provider-aws/aws
../../go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20191003145700-f8707a46c6ec/aws/resource_aws_datasync_task.go:102:9: undefined: datasync.PosixPermissionsBestEffort
```

I've tried a bunch of combinations, this seems to be the closest to functions. Do you happen to have a configuration that is currently functional for the aws provider?  Thanks!

**Comment by johandry** [comment]
Hi, thanks for the feedback, it's nice to know terranova is been used :) 

I'm using terranova with KubeKit on production (here is the [go.mod](https://github.com/liferaft/kubekit/blob/master/go.mod)) and we use:

```
require (
  ...
  github.com/aws/aws-sdk-go v1.25.4
  github.com/kubernetes-sigs/aws-iam-authenticator v0.3.1-0.20181019024009-82544ec86140
  github.com/terraform-providers/terraform-provider-aws v1.60.1-0.20191003145700-f8707a46c6ec
  ...
)
```

There are also some examples in the `terranova-examples` repository ([here](https://github.com/johandry/terranova-examples/)), all of them are using AWS however they are very simple examples.

May I see the `go.mod` file that you are using?

It may be related to version of `github.com/aws/aws-sdk-go/service/datasync` you are importing/requiring in the `go.mod` file. If you are using a version for `github.com/aws/aws-sdk-go` higher than `v1.25.4` then try to use `v1.25.4`.

```
require github.com/aws/aws-sdk-go v1.25.4
```

If you need higher than that, the last version where `datasync.PosixPermissionsBestEffort` is defined in `aws-sdk-go/service/datasync/api.go` is `v1.25.39`.

So, unfortunately the latest version of `github.com/aws/aws-sdk-go` you can use could be `v1.25.39`.

This bug is related to the feature in issue #26. Once this feature is done you can use any version of AWS you want.

**Comment by johandry** [comment]
Related to:

- Issue #26

**Comment by cacois** [comment]
@johandry  Excellent, thanks!  My issues was definitely the aws-sdk-go version - simple demo is working fine now!   Any chance terranova can work with alternate backends, or is that a feature not yet on the radar?

**Comment by johandry** [comment]
I haven't need it but all features request are welcome.

I'll check about it and add it as a feature :) 

Thanks for all the feedback and I'll work on the documentation too.
